//! Tree sprite atlas — loads pre-rendered Blender sprites embedded at compile time.
//!
//! The atlas binary is generated by:
//!   blender --background assets/blender/conifer.blend --python assets/blender/render_conifer.py
//!
//! Format: R | (G << 8) | (B << 16) | (HEIGHT << 24) per pixel, row-major, variant-major.
//! Index:  sprites[variant * SPRITE_SIZE^2 + y * SPRITE_SIZE + x]

pub const SPRITE_SIZE: u32 = 256;
pub const SPRITE_VARIANTS: u32 = 8;

/// Embedded atlas binary (2 MB, 8 variants × 256×256 × u32).
static ATLAS: &[u8] = include_bytes!("../assets/sprites/conifer_atlas_256.bin");

pub fn generate_tree_sprites() -> Vec<u32> {
    let total = (SPRITE_SIZE * SPRITE_SIZE * SPRITE_VARIANTS) as usize;
    let expected_bytes = total * 4;

    assert_eq!(
        ATLAS.len(),
        expected_bytes,
        "Sprite atlas size mismatch: expected {} bytes, got {}. Re-run render_conifer.py.",
        expected_bytes,
        ATLAS.len()
    );

    let mut data = vec![0u32; total];
    for (i, chunk) in ATLAS.chunks_exact(4).enumerate() {
        data[i] = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
    }
    data
}
